mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=false
    - MYSQL_USER=petc
    - MYSQL_PASSWORD=petc
    - MYSQL_DATABASE=petc
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
